name: Angular CI Pipeline

#Setup condition for trigger pipeline
on:
  push:
    branches: 
      [develop]
  pull_request:
    branches:
      [develop]

concurrency:
  group: ${{ github.workflow }}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci                 #Use exactly version in package-lock.json

      - name: Build Angular app
        run: npm run build -- --configuration=production
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build + push + remote cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tourism-fe:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/tourism-fe:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/tourism-fe:cache,mode=max
    
